version: '3.9'

services:
  db:
    platform: linux/arm64/v8
    image: arm64v8/mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    env_file:
      - .env

    networks:
      - web

  web:
    build: .
    networks:
      - web

    ports:
      - "5001:5001"
    volumes:
      - "./:/code"

networks:
  web:
    external: true
